# Source pins for the ROCm stream at version 7.13 (therock-7.13 tags).
# Generated by ./srcs-gen.py — do not edit by hand; re-run the generator.
# Minimal dev file: packages not listed here inherit their pin from baseSrcs.
{
  rocmVersion = "7.13";
  tagPrefix = "therock-";
  # Components that track the ROCm version but have no source on this
  # stream (no tag / project removed). default.nix marks these broken in
  # the scope rather than silently serving the stable version.
  brokenPackages = [
    "hipfort"
    "migraphx"
    "mivisionx"
    "rocalution"
    "rocmlir"
    "rpp"
  ];
  packages = {
    amdsmi = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/amdsmi"
        "shared"
      ];
      hash = "sha256-zqjKTn4wymnsq/f73oQFxzrrzz6oROo2/2rBfGUo1u0=";
      extraSrcs.esmi_ib = {
        owner = "amd";
        repo = "esmi_ib_library";
        rev = "esmi_pkg_ver-4.2";
        hash = "sha256-czF9ezkAO0PuDkXh8y639AcOZH+KVcWiXPX74H5W/nw=";
      };
    };
    aqlprofile = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/aqlprofile"
        "shared"
      ];
      hash = "sha256-z03HNx7TOB6V0eaVjkeir9ukvHgc99fSvbGrSqWx4DM=";
    };
    clr = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/clr"
        "shared"
      ];
      hash = "sha256-CpKFVpLedYY9FtfOFR2bypcrsL+B1l2CkAW5s01ZiVw=";
    };
    composable_kernel_base = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/composablekernel"
        "shared"
      ];
      hash = "sha256-TvFNVmODOxpfMeubVeJivhKWtlmE/0SOMB+dOTVJGBM=";
    };
    half = {
      version = "7.13";
      owner = "ROCm";
      repo = "half";
      rev = "therock-7.13";
      hash = "sha256-If9O5BEeymsLN+C0drZsPSxEWXpJTxeDBGNHNXSumm4=";
    };
    hip-common = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/hip"
        "shared"
      ];
      hash = "sha256-LL0kFJPZi+0PXHRcX0oyJWpRL4ZlfoZJdh9ibQ1Q3QE=";
    };
    hipblas = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/hipblas"
        "shared"
      ];
      hash = "sha256-BTIco9M86gtyk0WsZVlHOAWjvcwg/xUHs6fr9f1AJsE=";
    };
    hipblas-common = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/hipblas-common"
        "shared"
      ];
      hash = "sha256-rHGXUqQJvPZfz6+V8JjyaUBWIggAhSYyAHkS4wmIfrg=";
    };
    hipcub = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/hipcub"
        "shared"
      ];
      hash = "sha256-h7W/2n0ByuhxHUcnwMEwMliGTKxlf8wu+zXFtSgTKMg=";
    };
    hipfft = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/hipfft"
        "shared"
      ];
      fetchSubmodules = true;
      hash = "sha256-Ij3+ytSyI1RiIapJ1ixeD8Cvj8nHKeDTrO9Mfp3QQ8c=";
    };
    hipify = {
      version = "7.13";
      owner = "ROCm";
      repo = "HIPIFY";
      rev = "therock-7.13";
      hash = "sha256-P6xoQfXuCdLZMe1msIrjBF4LsrBihRQNwHczQ/KIxwM=";
    };
    hiprand = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/hiprand"
        "shared"
      ];
      hash = "sha256-t60P4tIEigix1Lns6D6OcMvRFOKO2vsjCqadM3VNu8I=";
    };
    hipsolver = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/hipsolver"
        "shared"
      ];
      hash = "sha256-OQw4gujyvMJviVBbj09Xr7WTNlOL9u2cY3x0PeHnAUM=";
    };
    hipsparse = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/hipsparse"
        "shared"
      ];
      hash = "sha256-+cKR+nfrv1pztN1EfG8enJFGEDlMC/KurFSVLwb4b4E=";
    };
    llvm = {
      version = "7.13";
      owner = "ROCm";
      repo = "llvm-project";
      rev = "therock-7.13";
      hash = "sha256-HT90H9iYf1gAnVFnxIVA+umB3WAlJ4MrszFcq3m8evA=";
      rocmLlvmVersion = "22.0.0-rocm";
    };
    miopen = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/miopen"
        "shared"
      ];
      fetchSubmodules = true;
      hash = "sha256-dt4Ro36YLu+M652yxp09QjtXv0YwAGc7sXYFRi3hOBE=";
    };
    rccl = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rccl"
        "shared"
      ];
      sourceRoot = "projects/rccl";
      hash = "sha256-stbhEylJIS3WesdYFWUIOxlVXozmP6ll5Vu66UhAu0E=";
    };
    rdc = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rdc"
        "shared"
      ];
      hash = "sha256-g+ftHskR4GR7UMGxadAN6jP86BNuTV7UbNz7ZdJEdNo=";
    };
    rocblas = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocblas"
        "shared"
      ];
      hash = "sha256-DZgH9eboIt1n7EBuDATHCEYflyaLbpf1G+MSPpqHb/k=";
    };
    rocdbgapi = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocdbgapi"
        "shared"
      ];
      sourceRoot = "projects/rocdbgapi";
      hash = "sha256-gRv4KFMXh3NCVOBVFZ1wbcRvNN7vIKMmlZl4+ZGSpX8=";
    };
    rocfft = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocfft"
        "shared"
      ];
      hash = "sha256-1qIQPlgV+O/EHYsxj/DUuQu10d0W7T32bZstiYH19WM=";
    };
    rocgdb = {
      version = "7.13";
      owner = "ROCm";
      repo = "ROCgdb";
      rev = "therock-7.13";
      hash = "sha256-Ixg6Y/STxokPL1b2N/FGoF3Z1pyPihFTKgxkl5huWA0=";
    };
    rocm-cmake = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-cmake";
      rev = "therock-7.13";
      hash = "sha256-im6UO0crO0Jc27zkTsdvJYPHit8IGlw/vDPGrmP1XqY=";
    };
    rocm-core = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocm-core"
        "shared"
      ];
      hash = "sha256-VyPfiYDtQBvcVqNCuWWRBX1YmJ/blM1nk8Ax+fHif7Y=";
    };
    rocm-runtime = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocr-runtime"
        "shared"
      ];
      hash = "sha256-EtF8pmL5K4a23RMls+Ky82C/jjOM2GHeT5Y5c9u0w2c=";
    };
    rocm-smi = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocm-smi-lib"
        "shared"
      ];
      hash = "sha256-StV9J8OqvfD41y+hzDczXfwt1aPHvLXVAqD1ka2TPhI=";
    };
    rocminfo = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocminfo"
        "shared"
      ];
      hash = "sha256-AFDYMrKmCBbMAJBaXLzeRxbcMKEMlpOxqNjsGf8gkx8=";
    };
    rocprim = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocprim"
        "shared"
      ];
      hash = "sha256-9ks3RcM2EGZvbw9+LDjz9X8C+PaMHDK0pZTEKiQTkGs=";
    };
    rocprofiler = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocprofiler"
        "shared"
      ];
      fetchSubmodules = true;
      hash = "sha256-SwcovAnCLk4AoY2rKUcK0hTHUhayhVD4UpyJyJa/uD4=";
    };
    rocprofiler-register = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocprofiler-register"
        "shared"
      ];
      hash = "sha256-MTYHsjtmaaWRsNdUmnSMYXt8eK6iRoF2vcf6gbGoCnE=";
    };
    rocprofiler-sdk = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocprofiler-sdk"
      ];
      fetchSubmodules = true;
      hash = "sha256-XkSw1foepep630xhsqjjwSKyn1BAIlODrxl9LtAAzIE=";
    };
    rocr-debug-agent = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocr-debug-agent"
        "shared"
      ];
      sourceRoot = "projects/rocr-debug-agent";
      hash = "sha256-P1OZgKw3Cpamt2m7uLUNk4BFnx9E3+XxM4/tCrdoK4M=";
    };
    rocrand = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocrand"
        "shared"
      ];
      hash = "sha256-W6T5cjnIUm50M3TqeYKhWrOTf8NH0F2NqyXUbm9caEY=";
    };
    rocsolver = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocsolver"
        "shared"
      ];
      hash = "sha256-0LBJbxWgqm5kCuOPD65+ittT9iJ9OW9Kbz8DFm01Y18=";
    };
    rocsparse = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocsparse"
        "shared"
      ];
      hash = "sha256-odDgHfKScxMRohFWR46yfxFgvbdjSM+n2GACoBCT2uY=";
    };
    rocthrust = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocthrust"
        "shared"
      ];
      hash = "sha256-T7eTtEl+6IlUtgrzRbr1oEjV3KEsjAWpE3XRhpJJtWo=";
    };
    roctracer = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-systems";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/roctracer"
        "shared"
      ];
      hash = "sha256-G8sT212v6hgfj5B/5t42JflIzWNvpvte7vialxMm0ZA=";
    };
    rocwmma = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "projects/rocwmma"
        "shared"
      ];
      hash = "sha256-hdoz/P9uY5h+63oR8iM71tk9srk9phutY5HR+mEwofU=";
    };
    tensile = {
      version = "7.13";
      owner = "ROCm";
      repo = "rocm-libraries";
      rev = "therock-7.13";
      sparseCheckout = [
        "shared/tensile"
        "shared"
      ];
      hash = "sha256-pAeyJhgMFtOT4Eg88QmmBYCc4SFczFxgJ2MBlTJ1H+8=";
    };
  };
}
